require('core.plugin_config.colorscheme')
require('core.plugin_config.lualine')
require('core.plugin_config.treesitter')
require('core.plugin_config.mason')
require('core.plugin_config.lsp_config')
require('core.plugin_config.completions')
require('core.plugin_config.which-key')
require('core.plugin_config.notify')
require('core.plugin_config.noice')
require('core.plugin_config.mini-pairs')
require('core.plugin_config.mini-surround')
require('core.plugin_config.mini-cursorword')
require('core.plugin_config.mini-indent-scope')
require('core.plugin_config.neodev')
require('core.plugin_config.colorizer')
require('core.plugin_config.indent-blankline')
require('core.plugin_config.gitsign')
require('core.plugin_config.alpha')
require('core.plugin_config.dap')
require('core.plugin_config.breadcrumbs')
require('core.plugin_config.oil')

-- INFO: Themes
require('core.plugin_config.themes.catppuccin')
require('core.plugin_config.themes.gruvbox')
require('core.plugin_config.themes.tokyo-night')
